### ISSUE TITLE
Track only PR changes

### ISSUE THREAD

**Issue by manuelmhtr** [joshmfrankel/simplecov-check-action#16]
Hi @joshmfrankel,
Thanks for building this amazing action. As an idea, it would be great to have an option to check coverage only agains changed files.

This could increase the adoption of existing projects with not enough coverage.

**Comment by gathuku** [comment]
@manuelmhtr Have you found any workaround on this?

**Comment by manuelmhtr** [comment]
@gathuku unfortunately no. I'd suggest starting with a very relaxed coverage policy (or ignoring some paths) and then moving gradually to your ideal policy.

**Comment by gathuku** [comment]
Sound cool @manuelmhtr , no problem.

**Comment by joshmfrankel** [comment]
@manuelmhtr has the approach I would take here. Gradual increase of the coverage threshold until you reach the desired amount. Changed files would be a great addition to the action. In theory, I believe you could diff the incoming Pull Request changed files from GitHub and compare it to the SimpleCov results and fail as necessary. I'd be willing to look over any PRs that implement this as I sadly don't have the time right now to build it :-(
