### ISSUE TITLE
Coverage report

### ISSUE THREAD

**Issue by rwehresmann** [joshmfrankel/simplecov-check-action#6]
I see this github action is being actively developed. Just would like to know: there are plans to add automatic reports? (e.g., something like https://github.com/marketplace/actions/simplecov-resultset-diff)

**Comment by joshmfrankel** [comment]
So for SimpleCov+ Action, the goal was to have the information output within the details' panel of GitHub actions for the current test run. This way, code inadequately tested would fail the CI check. Clicking the failed check sends you to the detail page, giving you a list of each file that failed to meet the minimum coverage threshold.

It looks like "SimpleCov Resultset Diff" creates a comment (like: https://github.com/DFE-Digital/simplecov-resultset-diff-action/blob/main/docs/splash.png) which gives the difference between test runs. Was the created comment what you meant by "automatic reports"? Or are you suggesting something else?

**Comment by joshmfrankel** [comment]
As of now there are no plans to add automatic reports to this action. PRs are welcome to implement this though :-)
